[build]
builder = "NIXPACKS"
# Remove "cd demo &&" because we are already in the demo folder
buildPlan.phases.build.cmds = ["mvn clean package -DskipTests"]

[deploy]
# Remove "demo/" prefix from the jar path
startCommand = "java -jar target/*.jar"
