[build]
builder = "NIXPACKS"
# This forces the builder to install JDK 21 before running Maven
nixpkgsArchive = "github:NixOS/nixpkgs/nixos-23.11" 

[build.phases.setup]
nixPkgs = ["jdk21_headless", "maven"]

[build.phases.build]
cmds = ["mvn clean package -DskipTests"]

[deploy]
startCommand = "java -jar target/*.jar"
